---
  name: run make and push to depenabot pr

  on: [pull_request]

  permissions: 
    pull-requests: write
    contents: write
    repository-projects: read
  jobs:
    run-make:
      name: Run make
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 2
      - name: Run make
        run: |
          make gen-purls
          cat purls.txt 
      - name: Checkout PR with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to fetch all branches
          ref: ${{ github.head_ref }}

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit updated purls.txt if changed
        run: |
          echo "purls.txt changed, committing..."
          git add purls.txt
          git diff --cached --quiet || git commit -m "chore: update purls.txt after dependency bump"
          git push origin HEAD
