
name: 'Dependency Review'

on:
  push:
    branches:
      - tesbranch 

permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      
      - name: Fetch main branch
        run: git fetch origin main

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          vulnerability-check: true
          base-ref: origin/main
          head-ref: ${{ github.sha }}

